---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


#Import the package

```{r setup}
library(naivebayesclassifier)
```


#TRAIN TEST SPLIT SCRIPT

```{r}
train_test <- function(data, train_size=0.7){
  set.seed(1)
  #use 70% of dataset as training set and 30% as test set
  sample <- sample(c(TRUE, FALSE), nrow(data), replace=TRUE, prob=c(train_size,1-train_size))
  train  <- data[sample, ]
  test   <- data[!sample, ]
  return (list(train= train, test= test))
}
```



#TEST 1: ON PATIENTS DATA (CHECK IF HAS ANXITY OR NOT)

```{r}
# root1= "/Users/wendyamyameogo/Downloads/ocd_patient_dataset.csv"
# ocd_patient= read.csv(root)
# 
# dff= train_test(ocd_patient)
# 
# Xtrain = dff$train %>% select(-c("Depression.Diagnosis", "Anxiety.Diagnosis", "OCD.Diagnosis.Date", "Patient.ID"))
# ytrain = dff$train[,"Anxiety.Diagnosis"]
# 
# Xtest = dff$test %>% select(-c("Depression.Diagnosis", "Anxiety.Diagnosis", "OCD.Diagnosis.Date", "Patient.ID"))
# ytest = dff$test[,"Anxiety.Diagnosis"]

```


# step 1: init the class with default naive bayes algorithm
## -> as its default it will use categorical naive bayes for non numeric and gauss for numeric values

```{r}
#obj1= naive_bayes_classifier$new(type = "default", smoothness = 1)
```


```{r}
#print(obj1)
```

# step 2 lets fit our training set

```{r}
#obj1$fit(Xtrain, ytrain)
```





#Test on bag of word document data frame


```{r}
#root= "/Users/wendyamyameogo/Desktop/SISE/NLP/td6/data_train.csv"
#df= read.csv(root, sep=";")
#head(df)
```

```{r}

```




```{r}
#test= naive_bayes_classifier$new(type="default")
```







